const $=s=>document.querySelector(s), esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const pools={all:'全部',candidates:'建仓候选',pullback_watch:'回踩观察',watchlist:'观察池',risk_samples:'风险样本',short_history_watch:'短历史'};
let report=null,reportId=null,funds=[],pool='all',page=1,view='all',selected=new Set(),favorites=new Set(JSON.parse(localStorage.getItem('fund-favorites')||'[]')),key=sessionStorage.getItem('fund-key')||'',jobTimer,cloud=false;
const pct=v=>Number.isFinite(v)?v.toFixed(2)+'%':'—'; const cls=v=>v>0?'positive':v<0?'negative':'';
function toast(s){$('#toast').textContent=s;$('#toast').style.display='block';setTimeout(()=>$('#toast').style.display='none',4000)}
function dialog(title,body){$('#dialogTitle').textContent=title;$('#dialogBody').innerHTML=body;if(!$('#dialog').open)$('#dialog').showModal()}
$('#closeDialog').onclick=()=>$('#dialog').close();$('#dialog').addEventListener('click',e=>{if(e.target===$('#dialog'))$('#dialog').close()});
async function api(path,body){const r=await fetch('/api/'+path,{method:body?'POST':'GET',headers:{'Content-Type':'application/json',Authorization:'Bearer '+key},...(body?{body:JSON.stringify(body)}:{})});const d=await r.json();if(!r.ok)throw Error(d.error||'服务请求失败');return d}
function valid(f){const a=['r1m','r3m','r6m','r1y'].map(k=>f.returns?.[k]);return a.every(Number.isFinite)&&a.every((v,i)=>!i||v>=a[i-1])}
function load(r,id=null){if(!r.stats||!Array.isArray(r.candidates))throw Error('请选择本软件生成的 JSON 报告');let f=[];for(const p of Object.keys(pools).slice(1))for(const x of r[p]||[]){if(!valid(x))throw Error('报告包含不符合永久收益规则的基金，已拒绝载入');f.push({...x,pool:p})}report=r;reportId=id;funds=[...new Map(f.map(x=>[x.code,x])).values()];selected.clear();page=1;$('#category').innerHTML='<option value="">全部分类</option>'+[...new Set(funds.map(f=>f.category))].sort().map(c=>`<option>${esc(c)}</option>`).join('');$('#signal').innerHTML='<option value="">全部信号</option>'+[...new Set(funds.map(f=>f.decision?.signal))].map(s=>`<option>${esc(s)}</option>`).join('');$('#reportMeta').textContent=`报告截止 ${r.end_date} · ${r.rule_version} · ${funds.length} 只展示基金（含风险样本）`;$('#stats').innerHTML=[['扫描基金',r.stats.universe,'全市场范围'],['详细分析',r.stats.evaluated,`失败 ${r.stats.detail_failures??0} 只`],['建仓候选',r.stats.candidates,'通过固定收益筛选'],['回踩观察',r.stats.pullback_watch,'等待入场条件确认']].map(([l,v,n])=>`<div class="stat"><div class="label">${l}</div><div class="value">${Number(v||0).toLocaleString()}</div><small>${n}</small></div>`).join('');$('#themes').innerHTML=[...new Set(funds.flatMap(f=>f.concepts||[]))].slice(0,18).map(c=>`<button class="theme" data-theme="${esc(c)}">${esc(c)} · ${funds.filter(f=>f.concepts?.includes(c)).length}</button>`).join('');const rej=Object.entries(r.reject_summary||{}).sort((a,b)=>b[1]-a[1]).slice(0,5);$('#rejects').innerHTML=rej.map(([k,v])=>`<div class="bar">${esc(k)}<span>${v}</span><i style="width:${Math.max(3,v/(rej[0]?.[1]||1)*100)}%"></i></div>`).join('');render()}
function filtered(){let q=$('#search').value.toLowerCase();let list=funds.filter(f=>(pool==='all'||f.pool===pool)&&(view!=='favorites'||favorites.has(f.code))&&(!$('#category').value||f.category===$('#category').value)&&(!$('#signal').value||f.decision.signal===$('#signal').value)&&(f.decision?.score??0)>=Number($('#score').value)&&(f.risk?.drawdown_1y??Infinity)<=Number($('#maxdd').value)&&[f.name,f.code,...(f.manager_names||[]),...(f.concepts||[])].join(' ').toLowerCase().includes(q));const s=$('#sort').value;return list.sort((a,b)=>s==='name'?a.name.localeCompare(b.name,'zh'):s==='dd'||s==='inception'?(a.risk?.[s==='dd'?'drawdown_1y':'drawdown_since_inception']??Infinity)-(b.risk?.[s==='dd'?'drawdown_1y':'drawdown_since_inception']??Infinity):s==='score'?(b.decision?.score??-Infinity)-(a.decision?.score??-Infinity):(b.returns?.[s]??-Infinity)-(a.returns?.[s]??-Infinity))}
function render(){if(!report)return;$('#tabs').innerHTML=Object.entries(pools).map(([p,n])=>`<button data-pool="${p}" class="${p===pool?'active':''}">${n} <small>${p==='all'?funds.length:funds.filter(f=>f.pool===p).length}</small></button>`).join('');const list=filtered(),size=+$('#pageSize').value,total=Math.max(1,Math.ceil(list.length/size));page=Math.min(page,total);$('#count').textContent=`匹配 ${list.length} 只`;$('#scoreValue').textContent=$('#score').value;$('#page').textContent=`${page} / ${total}`;$('#prev').disabled=page===1;$('#next').disabled=page===total;$('#empty').hidden=list.length>0;$('#compareCount').textContent=selected.size;$('#rows').innerHTML=list.slice((page-1)*size,page*size).map(f=>`<tr><td><input type="checkbox" aria-label="对比 ${esc(f.code)}" data-select="${f.code}" ${selected.has(f.code)?'checked':''}></td><td><button class="fundlink" data-detail="${f.code}">${esc(f.name)}</button><div class="fundmeta">${f.code} · ${esc((f.manager_names||[]).join(' / ')||'经理待核实')}</div></td><td><span class="score">${f.decision?.score??'—'}</span></td>${['r1m','r3m','r6m','r1y'].map(k=>`<td class="${cls(f.returns[k])}">${pct(f.returns[k])}</td>`).join('')}${['drawdown_1y','drawdown_3y','drawdown_since_inception'].map(k=>`<td>${pct(f.risk?.[k])}</td>`).join('')}<td><span class="badge ${f.decision?.signal==='可分批试仓'?'good':''}">${esc(f.decision?.signal)}</span></td><td><button class="star ${favorites.has(f.code)?'on':''}" aria-label="关注 ${f.code}" data-star="${f.code}">${favorites.has(f.code)?'★':'☆'}</button></td></tr>`).join('')}
for(const id of ['search','category','signal','sort','score','maxdd','pageSize'])$('#'+id).addEventListener('input',()=>{page=1;render()});$('#prev').onclick=()=>{page--;render()};$('#next').onclick=()=>{page++;render()};$('#reset').onclick=()=>{for(const id of ['search','category','signal'])$('#'+id).value='';$('#score').value=0;$('#maxdd').value=100;pool='all';page=1;render()};
document.addEventListener('click',e=>{const b=e.target.closest('button');if(!b)return;if(b.dataset.pool){pool=b.dataset.pool;page=1;render()}if(b.dataset.star){const c=b.dataset.star;favorites.has(c)?favorites.delete(c):favorites.add(c);localStorage.setItem('fund-favorites',JSON.stringify([...favorites]));render()}if(b.dataset.detail)detail(b.dataset.detail);if(b.dataset.theme){$('#search').value=b.dataset.theme;page=1;render()}if(b.dataset.view){view=b.dataset.view;document.querySelectorAll('.nav').forEach(n=>n.classList.toggle('active',n===b));$('#viewTitle').textContent=view==='favorites'?'我的关注':'基金候选池';page=1;render()}});
$('#rows').addEventListener('change',e=>{const c=e.target.dataset.select;if(!c)return;if(e.target.checked){if(selected.size===4){e.target.checked=false;return toast('一次最多对比 4 只基金')}selected.add(c)}else selected.delete(c);$('#compareCount').textContent=selected.size});
function detail(c){const f=funds.find(f=>f.code===c);dialog(f.name,`<p class="muted">${c} · ${esc(f.category)} · 净值日期 ${esc(f.nav_date)} · ${esc((f.manager_names||[]).join(' / '))}</p><div class="detail-grid">${[['近一年收益',f.returns.r1y],['近一年最大回撤',f.risk.drawdown_1y],['近三年最大回撤',f.risk.drawdown_3y],['成立以来最大回撤',f.risk.drawdown_since_inception]].map(([k,v])=>`<div><small>${k}</small><strong>${pct(v)}</strong></div>`).join('')}<div><small>综合评分</small><strong>${f.decision.score??'—'}</strong></div><div><small>信号</small><p>${esc(f.decision.signal)}</p></div></div><div class="detail-note">四周期收益硬规则：通过。${esc(pools[f.pool])} · 数据完整度 ${Math.round((f.data_quality?.completeness||0)*100)}% · 置信度 ${esc(f.data_quality?.confidence||'未知')}</div><section class="evidence"><h2>评估依据</h2><ul>${[...(f.decision.signal_reasons||[]),...(f.decision.score_notes||[]),...(f.decision.eligibility_blockers||[]),...(f.decision.eligibility_warnings||[])].map(t=>`<li>${esc(t)}</li>`).join('')}</ul><h2>数据来源与口径</h2>${Object.entries(f.provenance||{}).filter(([k])=>['r1y','drawdown','drawdown_3y','drawdown_since_inception','manager_names'].includes(k)).map(([k,v])=>`<p class="muted">${esc(k)} · ${esc(v.source)} · ${esc(v.as_of)}<br>${esc(v.note)}</p>`).join('')}<h2>已披露重仓</h2><p>${(f.holdings||[]).map(h=>`${esc(h.name)} ${esc(h.ratio)}`).join('　')||'暂无披露'}</p><p class="muted">重仓披露有滞后，不代表当前实时持仓。成立不足三年时，三年回撤为可得历史窗口。</p></section>`)}
$('#compareNav').onclick=()=>{if(selected.size<2)return toast('请在表格勾选 2–4 只基金');const fs=funds.filter(f=>selected.has(f.code));const metrics=[['基金经理',f=>(f.manager_names||[]).join('/')],['信号',f=>f.decision.signal],['综合评分',f=>f.decision.score],...['r1m','r3m','r6m','r1y'].map((k,i)=>[['近1月','近3月','近6月','近1年'][i],f=>pct(f.returns[k])]),...['drawdown_1y','drawdown_3y','drawdown_since_inception'].map((k,i)=>[['一年回撤','三年回撤','成立以来回撤'][i],f=>pct(f.risk[k])]),['净值日期',f=>f.nav_date]];dialog('基金横向对比',`<div class="table-wrap"><table class="compare-table"><tr><th>指标</th>${fs.map(f=>`<th>${esc(f.name)}<br>${f.code}</th>`).join('')}</tr>${metrics.map(([n,fn])=>`<tr><td>${n}</td>${fs.map(f=>`<td>${esc(fn(f))}</td>`).join('')}</tr>`).join('')}</table></div><p class="muted">按相同历史指标比较，不构成收益预测。</p>`)};
function download(name,text,type){const u=URL.createObjectURL(new Blob([text],{type}));const a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),1000)}
$('#exportBtn').onclick=()=>{const cell=v=>'"'+String(v??'').replace(/^[=+@-]/,"'$&").replaceAll('"','""')+'"';const lines=[['代码','基金','经理','信号','评分','近1月','近3月','近6月','近1年','一年最大回撤','三年最大回撤','成立以来最大回撤'],...filtered().map(f=>[f.code,f.name,(f.manager_names||[]).join('/'),f.decision.signal,f.decision.score,...['r1m','r3m','r6m','r1y'].map(k=>f.returns[k]),...['drawdown_1y','drawdown_3y','drawdown_since_inception'].map(k=>f.risk[k])])];download('基金筛选-'+report.end_date+'.csv','\ufeff'+lines.map(r=>r.map(cell).join(',')).join('\r\n'),'text/csv')};
$('#importBtn').onclick=()=>$('#importFile').click();$('#importFile').onchange=async e=>{try{load(JSON.parse(await e.target.files[0].text()));$('#notice').textContent='本地导入报告 · 仅在当前浏览器查看；云端邮件请选取云端报告。';toast('报告已导入')}catch(e){toast(e.message)}};
$('#methodBtn').onclick=()=>dialog('固定策略与使用口径','<p>永久硬规则：近1月 ≤ 近3月 ≤ 近6月 ≤ 近1年。缺失数据不能当成负收益，也不能自动视为买点。</p><ul><li>所有基金统一按未持仓评估，仅输出五种既定信号。</li><li>入池资格、综合评分、交易信号独立；近1周进入风控。</li><li>近一年最大回撤统一 13% 上限；风险样本单列供研究，不是建仓推荐。</li><li>以原始累计净值序列计算回撤，按净值日期截取窗口；三年窗口含起点前交易日。具体来源见基金详情。</li><li>同一底层策略不同份额去重；每次保留历史快照。</li><li>网页沿用 V2.5 核心。全市场扫描不等于对每只基金都做详情分析，详情上限为 1,800 只。</li></ul>');
$('#settingsBtn').onclick=()=>{dialog('连接与设置',`<div class="form"><p>连接后可发起云端扫描、读取历史报告和发送邮件。访问口令仅保存在本次浏览器会话，邮件及 GitHub 密钥只在云端配置。</p><label>研究台访问口令<input id="key" type="password" autocomplete="off" value="${esc(key)}"></label><button class="primary" id="saveKey">连接研究台</button><p id="connection" class="muted">尚未检测</p></div>`);$('#saveKey').onclick=async()=>{key=$('#key').value;sessionStorage.setItem('fund-key',key);try{const s=await api('status');cloud=true;$('#connection').textContent=`数据库 ${s.database?'已连接':'未配置'} · 扫描 ${s.scanner?'已配置':'未配置'} · 邮件 ${s.email?'已配置':'未配置'}`;toast('已连接');await latest()}catch(e){$('#connection').textContent=e.message}}};
async function latest(){try{const d=await api('reports');if(d.length){const r=await api('reports/'+d[0].id);load(r,d[0].id);$('#notice').textContent='云端报告 · 截止 '+r.end_date+' · 请核对各基金净值日期'}return d}catch(e){throw e}}
$('#historyBtn').onclick=async()=>{try{const d=await api('reports');dialog('历史报告',d.length?d.map(r=>`<div class="history-row"><span>${esc(r.date)} · ${esc(r.created)}<br><small>${esc(r.id)}</small></span><button data-open="${esc(r.id)}">查看报告</button></div>`).join(''):'还没有云端报告，请先发起扫描。');$('#dialogBody').onclick=async e=>{if(e.target.dataset.open){try{const id=e.target.dataset.open;load(await api('reports/'+id),id);$('#notice').textContent='云端历史报告 · '+report.end_date;$('#dialog').close()}catch(e){toast(e.message)}}}}catch(e){toast(e.message+'；请先连接研究台')}};
$('#scanBtn').onclick=()=>{const today=new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Shanghai'}).format(new Date());dialog('发起全市场扫描',`<div class="form"><p>云端运行原版策略，通常需要数分钟，数据源较慢时可能更久。可以关闭网页，稍后从历史报告查看。</p><label>截止日期<input id="runDate" type="date" value="${today}" max="${today}"></label><label><span><input type="checkbox" id="autoEmail" checked> 完成后自动发送到预设邮箱</span></label><button class="primary" id="startJob">开始扫描</button><p id="jobText" role="status"></p></div>`);$('#startJob').onclick=async()=>{try{$('#startJob').disabled=true;const j=await api('jobs',{date:$('#runDate').value,email:$('#autoEmail').checked});sessionStorage.setItem('fund-job',j.id);$('#jobText').textContent='任务已提交，等待云端启动';poll(j.id)}catch(e){$('#jobText').textContent=e.message;$('#startJob').disabled=false}}};
function poll(id){clearTimeout(jobTimer);api('jobs/'+id).then(async j=>{const txt=`${j.status} · ${j.message||''}`;$('#notice').textContent=txt;if($('#jobText'))$('#jobText').textContent=txt;if(j.status==='completed'){sessionStorage.removeItem('fund-job');load(await api('reports/'+id),id);toast('报告已生成；邮件状态：'+(j.email_status||'未发送'));return}if(j.status==='failed'){sessionStorage.removeItem('fund-job');return}jobTimer=setTimeout(()=>poll(id),5000)}).catch(e=>{$('#notice').textContent='状态连接中断：'+e.message+'。可稍后查看历史。';jobTimer=setTimeout(()=>poll(id),15000)})}
$('#emailBtn').onclick=()=>{if(!reportId)return toast('示例或本地报告未存入云端，请先扫描或选择云端历史报告');dialog('发送正式报告',`<p>发送完整报告到云端配置的固定收件邮箱。当前筛选不影响邮件内容。</p><button class="primary" id="sendMail">确认发送</button><p id="mailState"></p>`);$('#sendMail').onclick=async()=>{try{$('#sendMail').disabled=true;const d=await api('email',{reportId});$('#mailState').textContent=d.message}catch(e){$('#mailState').textContent=e.message;$('#sendMail').disabled=false}}};
fetch('sample.json').then(r=>r.json()).then(r=>{load(r);$('#notice').textContent='历史示例 · '+r.end_date+'，不是今日数据。连接云端后可生成最新报告。';if(key)latest().catch(e=>toast(e.message));const j=sessionStorage.getItem('fund-job');if(j&&key)poll(j)}).catch(e=>{$('#notice').textContent='示例载入失败：'+e.message});
